### ISSUE TITLE
这是什么  ？  如何启用演示？

### ISSUE THREAD

**Issue by xiaolongyuan** [okoala/vue-antd#1]

**Comment by xiaolongyuan** [comment]
这是 ant-design 的vue版本？

**Comment by okoala** [comment]
@xiaolongyuan  对的，目前还在开发阶段~你可以尝试运行 npm run docs

**Comment by xiaolongyuan** [comment]
运行不了 报错
‘’‘
 harp server ./.temp --port 8002 & webpack --config build/webpack.config.js --progress --colors --watch

'harp' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒                            Hash: b4feb4eca3ffacdcacd6
Version: webpack 1.12.2
Time: 9754ms
      Asset     Size  Chunks             Chunk Names
     app.js   790 kB       0  [emitted]  app
    app.css   230 kB       0  [emitted]  app
 app.js.map   971 kB       0  [emitted]  app
app.css.map   429 kB       0  [emitted]  app
 index.html  12.7 kB          [emitted]
    + 372 hidden modules

WARNING in ./src/components/table/index.js

D:\Workspace\webapp\vue-antd\src\components\table\index.js
  8:1  error  Multiple blank lines not allowed  no-multiple-empty-lines

✖ 1 problem (1 error, 0 warnings)


ERROR in ./docs/styles/images/vue.png
Module build failed: Error: spawn D:\Workspace\webapp\vue-antd\node_modules\image-webpack-loader\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor\optipng.exe ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
 @ ./~/html-loader!./~/vue-antd-docs-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./docs/views/docs/introduce.vue 1:322-360
Child extract-text-webpack-plugin:
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 74 hidden modules
[BS] [info] Proxying: http://localhost:8002
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.199.78:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.199.78:3001
 ---------------------------------------

’‘’

**Comment by okoala** [comment]
@xiaolongyuan  你安装下harp    ```npm i harp -g```

**Comment by xiaolongyuan** [comment]
这玩意是不是限制node版本的 我的版本是 4.0+

**Comment by okoala** [comment]
@xiaolongyuan   我本地是4.2.1，Mac系统。   你现在先别用呗，等我把常用组件都完善下~~

**Comment by xiaolongyuan** [comment]
哈哈 先看看文档  有机会弄弄pr也是好的啊

**Comment by okoala** [comment]
@xiaolongyuan  赞~~

**Comment by xiaolongyuan** [comment]
https://gitter.im  创建个repo聊天室吧
