### ISSUE TITLE
多层的 slot 引用 有错误？？ 

### ISSUE THREAD

**Issue by newset** [okoala/vue-antd#9]
在做menu 里面的内容， base/menu 里面 slot 渲染的是上一层的元素？这个是在哪里定义的？是 slotminxs 吗？

**Comment by okoala** [comment]
@newset menu还没弄好~~

**Comment by newset** [comment]
@okoala 我主要想问那个 slot 是不是有问题？在哪里？

**Comment by newset** [comment]
@okoala 找到问题了，slot 没错，是文档里面写错了

**Comment by newset** [comment]
@okoala 能加个 contributtor不？

**Comment by xiaolongyuan** [comment]
@newset 你居然能用了 怎么用的？

**Comment by newset** [comment]
@xiaolongyuan 我在写 menu 的部分

**Comment by xiaolongyuan** [comment]
@newset  一直是
ERROR in ./~/vue-antd/index.js
Module parse failed: C:\Workspace\WebstormProjects\web-shop-admin\node_modules\vue-antd\index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import './style/index.less'
| import meta from './package.json'
| import * as utils from './utils'
 @ ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/home/welcome.vue 7:15-34

**Comment by newset** [comment]
@xiaolongyuan 你需要 less-loader 吧

**Comment by xiaolongyuan** [comment]
@newset  配了             { test: /\.less$/, loader: "style!css!less" },

**Comment by xiaolongyuan** [comment]
package.json     
   "less": "^2.5.3",
    "less-loader": "^2.2.1",

**Comment by newset** [comment]
@xiaolongyuan 我没遇到这个问题，只有个 sourcemap 的问题，然我给直接去掉了

**Comment by newset** [comment]
less 我是全局安装，用的 mac， windows 不知道怎么回事的

**Comment by xiaolongyuan** [comment]
@newset 是的 真是奇怪
